
import appData from './app.json'
export const config = {
	SDKAppID: 20006203,
	secretKey: "",
	appName: 'im',
	logo: '',
	channel: appData.channel
}
const CMD_TYPE={
	cmd:'',// delete_message=>删除消息  delete_user=>删除用户  ban_user=>禁言用户  refresh_friend_list=>获取好友列表
	Args:[]  // Arrary  
}
export const fileType=[
	{icon:'tb_html',arr:['html','css','js','java','py']},
	{icon:'tb_music',arr:['mp3','wav','aac']},
	{icon:'tb_others',arr:['']},
	{icon:'tb_tpwj',arr:['jpg','png','gif','bmp','jpeg']},
	{icon:'tb_video',arr:['mp4','avi','mov']},
	{icon:'tb_wbwj',arr:['txt','docx','pptx','xlsx','pd']},
	{icon:'tb_yswj',arr:['zip','rar']},
	// {icon:'tb_wbwj',arr:['zip','rar']},
]
export const colors = [
	// 'linear-gradient(180deg, rgba(22, 217, 227, 1) 0%, rgba(48, 199, 236, 1) 47%, rgba(70, 174, 247, 1) 100%)',
	//  'linear-gradient(180deg, rgba(72, 198, 239, 1) 0%, rgba(111, 134, 214, 1) 100%)',
	//  "linear-gradient(180deg, rgba(0, 122, 222, 1) 0%, rgba(0, 236, 188, 1) 100%)",
	//  "linear-gradient(180deg, rgba(55, 236, 186, 1) 0%, rgba(114, 175, 211, 1) 100%)",
	//  "linear-gradient(180deg, rgba(84, 190, 72, 1) 0%, rgba(161, 250, 97, 1) 100%)",
	//  "linear-gradient(180deg, rgba(247, 140, 160, 1) 0%, rgba(141, 80, 199, 1) 100%)",
	//  "linear-gradient(180deg, rgba(250, 131, 164, 1) 0%, rgba(225, 96, 127, 1) 100%)",
	//  "linear-gradient(180deg, rgba(176, 144, 247, 1) 0%, rgba(120, 105, 227, 1) 100%)",
	//  "linear-gradient(180deg, rgba(48, 194, 135, 1) 0%, rgba(167, 254, 102, 1) 100%)",
	//  "linear-gradient(180deg, rgba(255, 182, 13, 1) 0%, rgba(255, 219, 25, 1) 100%)",
	//  "linear-gradient(180deg, rgba(0, 201, 254, 1) 0%, rgba(75, 156, 241, 1) 100%)",
	//  " linear-gradient(180deg, rgba(255, 68, 102, 1) 0%, rgba(255, 158, 151, 1) 100%)",
	//  "linear-gradient(180deg, rgba(220, 91, 74, 1) 0%, rgba(250, 126, 91, 1) 100%)",
	//  "linear-gradient(180deg, rgba(196, 113, 245, 1) 0%, rgba(250, 113, 205, 1) 100%)",
	//  "linear-gradient(270deg, rgba(106, 133, 182, 1) 0%, rgba(186, 200, 224, 1) 100%)",
	//  "linear-gradient(180deg, rgba(246, 211, 101, 1) 0%, rgba(253, 160, 133, 1) 100%)",
	//  "linear-gradient(180deg, rgba(255, 88, 88, 1) 0%, rgba(240, 152, 25, 1) 100%)",
	//  "linear-gradient(180deg, rgba(252, 203, 144, 1) 0%, rgba(213, 126, 235, 1) 100%)",
//  'linear-gradient(180deg, rgba(102, 126, 234, 1) 0%, rgba(118, 75, 162, 1) 100%)'


	'linear-gradient(180deg, rgba(22, 217, 227, 1) 0%, rgba(36, 138, 212, 1) 100%)',
	 'linear-gradient(180deg, rgba(72, 198, 239, 1) 0%, rgba(86, 109, 191, 1) 100%)',
	 'linear-gradient(180deg, rgba(0, 122, 222, 1) 0%, rgba(0, 236, 188, 1) 100%)',
	 'linear-gradient(180deg, rgba(55, 236, 186, 1) 0%, rgba(7, 124, 148, 1) 100%)',
	 'linear-gradient(180deg, rgba(161, 250, 97, 1) 0%, rgba(58, 173, 45, 1) 100%)',
	 'linear-gradient(180deg, rgba(247, 140, 160, 1) 0%, rgba(141, 80, 199, 1) 100%)',
	 'linear-gradient(180deg, rgba(255, 128, 164, 1) 0%, rgba(207, 68, 100, 1) 100%)',
	 'linear-gradient(180deg, rgba(176, 144, 247, 1) 0%, rgba(88, 79, 161, 1) 100%)',
	 'linear-gradient(180deg, rgba(150, 255, 69, 1) 0%, rgba(37, 138, 97, 1) 100%)',
	 'linear-gradient(180deg, rgba(255, 219, 25, 1) 0%, rgba(217, 119, 0, 1) 100%)',
	 'linear-gradient(180deg, rgba(0, 201, 254, 1) 0%, rgba(56, 74, 156, 1) 100%)',
	 'linear-gradient(180deg, rgba(255, 167, 161, 1) 0%, rgba(194, 58, 83, 1) 100%)',
	 'linear-gradient(180deg, rgba(250, 126, 91, 1) 0%, rgba(199, 62, 44, 1) 100%)',
	 'linear-gradient(180deg, rgba(240, 122, 201, 1) 0%, rgba(151, 86, 186, 1) 100%)',
	 'linear-gradient(180deg, rgba(177, 200, 240, 1) 0%, rgba(67, 95, 148, 1) 100%)',
	 'linear-gradient(180deg, rgba(246, 211, 101, 1) 0%, rgba(247, 124, 87, 1) 100%)',
	 'linear-gradient(180deg, rgba(240, 209, 53, 1) 0%, rgba(230, 106, 106, 1) 100%)',
	 'linear-gradient(180deg, rgba(255, 195, 122, 1) 0%, rgba(177, 81, 196, 1) 100%)',
	 'linear-gradient(180deg, rgba(130, 151, 245, 1) 0%, rgba(109, 66, 153, 1) 100%)'
]
export const AREA_LIST = [{
		zhName: '中国',
		areaCode: '86',
		enName: 'China',
		language: '中文',
		localCurrency: 'CNY',
		sort: 500,
		sysLanguage: 'zh',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '美国',
		areaCode: '1',
		enName: 'USA',
		language: '英文',
		localCurrency: 'USD',
		sort: 499,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '葡萄牙',
		areaCode: '351',
		enName: 'Portugal',
		language: 'en_US',
		localCurrency: 'USD',
		sort: 377,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '尼日利亚',
		areaCode: '234',
		enName: 'Nigeria',
		language: 'en_US',
		localCurrency: 'USD',
		sort: 365,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '阿拉伯埃及共和国',
		areaCode: '20',
		enName: 'El Minya',
		language: 'en_US',
		localCurrency: 'USD',
		sort: 333,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '约旦',
		areaCode: '962',
		enName: 'Jordan',
		language: 'en_US',
		localCurrency: 'USD',
		sort: 324,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '孟加拉国',
		areaCode: '880',
		enName: 'Bangladesh',
		language: 'en_US',
		localCurrency: 'BDT',
		sort: 235,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '摩洛哥',
		areaCode: '212',
		enName: 'Morocco',
		language: 'en_US',
		localCurrency: 'MAD',
		sort: 234,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '津巴布韦',
		areaCode: '263',
		enName: 'Republic of Zimbabwe',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 233,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '沙特阿拉伯',
		areaCode: '966',
		enName: 'Saudi Arabia',
		language: 'ar_SA',
		localCurrency: 'SAR',
		sort: 232,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '越南',
		areaCode: '84',
		enName: 'Vietnam',
		language: 'vi_VN',
		localCurrency: 'VND',
		sort: 231,
		sysLanguage: 'vi',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '印尼',
		areaCode: '62',
		enName: 'Indonesia',
		language: '印尼语',
		localCurrency: 'IDR',
		sort: 230,
		sysLanguage: 'id',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '乌拉圭',
		areaCode: '598',
		enName: 'Uruguay',
		language: 'en_US',
		localCurrency: 'UYU',
		sort: 227,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '英国',
		areaCode: '44',
		enName: 'United Kingdom',
		language: 'en_US',
		localCurrency: 'GBP',
		sort: 225,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '菲律宾',
		areaCode: '63',
		enName: 'Philippines',
		language: 'en_US',
		localCurrency: 'PHP',
		sort: 213,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '瑞士',
		areaCode: '41',
		enName: 'Switzerland',
		language: 'fr-fr',
		localCurrency: 'CHF',
		sort: 212,
		sysLanguage: 'fr',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '瑞典',
		areaCode: '46',
		enName: 'Sweden',
		language: 'en_US',
		localCurrency: 'SEK',
		sort: 211,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '韩国',
		areaCode: '82',
		enName: 'South Korea',
		language: 'en_US',
		localCurrency: 'KRW',
		sort: 201,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '阿联酋',
		areaCode: '971',
		enName: 'UAE',
		language: 'en_US',
		localCurrency: 'AED',
		sort: 196,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '新加坡',
		areaCode: '65',
		enName: 'Singapore',
		language: 'en_US',
		localCurrency: 'SGD',
		sort: 195,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '俄罗斯',
		areaCode: '7',
		enName: 'Russia',
		language: 'en_US',
		localCurrency: 'RUB',
		sort: 187,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '秘鲁',
		areaCode: '51',
		enName: 'Peru',
		language: 'en_US',
		localCurrency: 'PEN',
		sort: 177,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '巴基斯坦',
		areaCode: '92',
		enName: 'Pakistan',
		language: 'en_US',
		localCurrency: 'PKR',
		sort: 173,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '土耳其',
		areaCode: '90',
		enName: 'Turkey',
		language: 'en_US',
		localCurrency: 'TUR',
		sort: 172,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '挪威',
		areaCode: '47',
		enName: 'Norway',
		language: 'en_US',
		localCurrency: 'NOK',
		sort: 171,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '新西兰',
		areaCode: '64',
		enName: 'new Zealand',
		language: 'en_US',
		localCurrency: 'NZD',
		sort: 166,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '荷兰',
		areaCode: '31',
		enName: 'Netherlands',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 165,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '缅甸',
		areaCode: '95',
		enName: 'Myanmar',
		language: 'zh_CN',
		localCurrency: 'MMK',
		sort: 159,
		sysLanguage: 'zh',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '墨西哥',
		areaCode: '52',
		enName: 'Mexico',
		language: 'en_US',
		localCurrency: 'MXN',
		sort: 153,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '老挝',
		areaCode: '856',
		enName: 'Laos',
		language: 'en_US',
		localCurrency: 'LAK',
		sort: 150,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '西班牙',
		areaCode: '34',
		enName: 'Spain',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 147,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '柬埔寨',
		areaCode: '855',
		enName: 'Cambodia',
		language: 'en_US',
		localCurrency: 'KHR',
		sort: 146,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '泰国',
		areaCode: '66',
		enName: 'Thailand',
		language: '泰语',
		localCurrency: 'THB',
		sort: 146,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '马耳他',
		areaCode: '356',
		enName: 'Malta',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 145,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '马来西亚',
		areaCode: '60',
		enName: 'Malaysia',
		language: 'en_US',
		localCurrency: 'MYR',
		sort: 142,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '卢森堡',
		areaCode: '352',
		enName: 'Luxembourg',
		language: 'fr-fr',
		localCurrency: 'EUR',
		sort: 138,
		sysLanguage: 'fr',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '日本',
		areaCode: '81',
		enName: 'Japan',
		language: 'en_US',
		localCurrency: 'JPY',
		sort: 124,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '意大利',
		areaCode: '39',
		enName: 'Italy',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 121,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '印度',
		areaCode: '91',
		enName: 'India',
		language: 'en_US',
		localCurrency: 'INR',
		sort: 116,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '爱尔兰',
		areaCode: '353',
		enName: 'Ireland',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 115,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '冰岛',
		areaCode: '354',
		enName: 'Iceland',
		language: 'en_US',
		localCurrency: 'ISK',
		sort: 114,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '匈牙利',
		areaCode: '36',
		enName: 'Hungary',
		language: 'en_US',
		localCurrency: 'HUF',
		sort: 113,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '圭亚那',
		areaCode: '592',
		enName: 'Guyana',
		language: 'en_US',
		localCurrency: 'GYD',
		sort: 110,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '德国',
		areaCode: '49',
		enName: 'Germany',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 101,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '法国',
		areaCode: '33',
		enName: 'France',
		language: 'fr-fr',
		localCurrency: 'EUR',
		sort: 96,
		sysLanguage: 'fr',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '芬兰',
		areaCode: '358',
		enName: 'Finland',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 95,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '厄瓜多尔',
		areaCode: '593',
		enName: 'Ecuador',
		language: 'en_US',
		localCurrency: 'USD',
		sort: 86,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '丹麦',
		areaCode: '45',
		enName: 'Denmark',
		language: 'en_US',
		localCurrency: 'DKK',
		sort: 80,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '塞浦路斯',
		areaCode: '357',
		enName: 'Cyprus',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 78,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '古巴',
		areaCode: '53',
		enName: 'Cuba',
		language: 'en_US',
		localCurrency: 'CUP',
		sort: 77,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '哥伦比亚',
		areaCode: '57',
		enName: 'Colombia',
		language: 'en_US',
		localCurrency: 'COP',
		sort: 70,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '智利',
		areaCode: '56',
		enName: 'Chile',
		language: 'en_US',
		localCurrency: 'CLF',
		sort: 66,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '加拿大',
		areaCode: '1',
		enName: 'Canada',
		language: 'en_US',
		localCurrency: 'CAD',
		sort: 61,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '保加利亚',
		areaCode: '359',
		enName: 'Bulgaria',
		language: 'en_US',
		localCurrency: 'BGN',
		sort: 57,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '巴西',
		areaCode: '55',
		enName: 'Brazil',
		language: 'pt-PT',
		localCurrency: 'BRL',
		sort: 55,
		sysLanguage: 'pt',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '玻利维亚',
		areaCode: '591',
		enName: 'Bolivia',
		language: 'en_US',
		localCurrency: 'BOV',
		sort: 53,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '奥地利',
		areaCode: '43',
		enName: 'Austria',
		language: 'en_US',
		localCurrency: 'EUR',
		sort: 41,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '澳大利亚',
		areaCode: '61',
		enName: 'Australia',
		language: 'en_US',
		localCurrency: 'AUD',
		sort: 40,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '阿根廷',
		areaCode: '54',
		enName: 'Argentina',
		language: 'en_US',
		localCurrency: 'ARS',
		sort: 36,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '阿尔巴尼亚',
		areaCode: '355',
		enName: 'Albania',
		language: 'en_US',
		localCurrency: 'ALL',
		sort: 31,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '澳门',
		areaCode: '853',
		enName: 'Macau',
		language: 'en_US',
		localCurrency: 'MOP',
		sort: 4,
		sysLanguage: 'en',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '香港',
		areaCode: '852',
		enName: 'HongKong',
		language: 'zh_HK',
		localCurrency: 'HKD',
		sort: 3,
		sysLanguage: 'hk',
		status: 1,
		nationalUrl: '1'
	},
	{
		zhName: '中国台湾',
		areaCode: '886',
		enName: 'Taiwan',
		language: 'zh_HK',
		localCurrency: 'TWD',
		sort: 2,
		sysLanguage: 'hk',
		status: 1,
		nationalUrl: '1'
	}
]